name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "unverified"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What part of the bot are you seeing the problem on?
      multiple: true
      options:
        - Game - Narrator
        - Game - Player
        - Economy
        - Other
  - type: textarea
    id: gamecode
    attributes:
      label: Game Code
      description: If this is a bug in a game, what was the game code?
    validations:
      required: false
