name: Suggestion
description: Add a suggestion
labels: ["Suggestion"]
body:
  - type: textarea
    id: suggestion
    attributes:
      label: What is your suggestion?
      description: Include all the details you have.
      value: "Things should happen!"
    validations:
      required: true
  - type: dropdown
    id: fromwhere
    validations:
      required: true
    attributes:
      label: Where is this suggestion from?
      options:
        - Staff Vote
        - Community Vote
        - Dev Assistant
        - Other
